### ISSUE TITLE
Unable to open the Page

### ISSUE THREAD

**Issue by TechDoodie** [CyberTitus/GPhisher-v2#4]
Hello there,
I was able to follow the instructions and fix the dependencies and I see what link is it running on. If I go to that link, I do not see anything now please help me.

**Comment by AbdulRKB** [comment]
Hello, I think that your port **80** is already taken by another program with is stopping flask from hosting local server at that port, to avoid this you can go to the [Last Line](https://github.com/CyberTitus/GPhisher-v2/blob/ae80a9d9d41b9e31780154274ba51f024802b46b/app.py#L44) of the code and change the port **80** to any other number between **5000-5100** or you can disable the other software.

_If that doesn't fix the problem, make sure that you are accessing the link from the same network (i.e. same WiFi): using a proxy sometimes may also cause problems._


_If you want to access from the different internet network, try using the main [GPhisher](https://github.com/CyberTitus/GPhisher)._
